services:

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: sgevendb
      POSTGRES_USER: sgevenuser
      POSTGRES_PASSWORD: kLLsBEzoQOSIYsO2xUF6cWpuDgNMCWlV
      DB_HOST: dpg-cu7c02ggph6c73b9tv2g-a
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sgeven-core:
    build: .
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: sgevendb
      DB_USER: sgevenuser
      DB_PASSWORD: kLLsBEzoQOSIYsO2xUF6cWpuDgNMCWlV
      DB_HOST: dpg-cu7c02ggph6c73b9tv2g-a
      DB_PORT: 5432

volumes:
  postgres_data: